### ISSUE TITLE
Do not use "cache" fetch policy when making GraphQL requests in client-admin app

### ISSUE THREAD

**Issue by machi1990** [aerogear/OpenVolunteerPlatform#39] opened 2020-04-30 11:52 UTC
The admin app should always retrieve up to date data. 

While doing this issue, we should also:
- remove cache from client config
- remove offix

**Comment by machi1990** [comment] 2020-04-30 11:53
Taking this one for myself.

**Comment by machi1990** [comment] 2020-05-04 11:35
So after reading this detailed article by our very own @wtrocki I think we can go with `network-only`. I'll change it a bit later.

**Comment by wtrocki** [comment] 2020-05-04 11:37
Duplicate of issue where we should remove cache completely

**Closed** 2020-05-04 14:01 UTC
